# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_room', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='MapRoom',
        ),
    ]
