# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_room', '0002_auto_20161026_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='maproom',
            name='center_lat',
            field=models.FloatField(default=-122.3321),
        ),
        migrations.AddField(
            model_name='maproom',
            name='center_lng',
            field=models.FloatField(default=47.6062),
        ),
        migrations.AddField(
            model_name='maproom',
            name='zoom_level',
            field=models.IntegerField(default=13),
        ),
    ]
