# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-12 17:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_room', '0003_auto_20161105_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='maproom',
            name='center_lat',
            field=models.FloatField(default=47.6062),
        ),
        migrations.AlterField(
            model_name='maproom',
            name='center_lng',
            field=models.FloatField(default=-122.3321),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='map_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_room.MapRoom'),
        ),
    ]
