# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-03 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_room', '0007_auto_20161130_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
