# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_room', '0009_auto_20161206_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='maproom',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='geojsonfile',
            name='map_room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='map_room.MapRoom'),
        ),
    ]
